# 全息渲染默认参数配置
image_file: input.jpg
depth_file: depth.png
output_file: output_hologram.png
output_width: 1440
output_height: 2560
threshold: 15.0
protrude: 0
line_number: 19.61603
obliquity: 0.101593
deviation: 15.83299625
scale_x: 1.0
scale_y: 1.0
offset_x: 0.0
offset_y: 0.0
blur_size: 10.0
blur_depth: 0.0
depth_image_blur_size: 50.0
border_color: "#FFFFFF"
border_size_x: 0.02
border_size_y: 0.01
